language: c
dist: bionic
sudo: false
os:
  - linux
  - osx

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
  apt:
    packages:
      - llvm
      - lld
      - clang
      - qemu

install:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then pyenv global 3.7.1; fi"
  - pip3 install -r tools/requirements.txt

script:
  - ./tools/buildconfig.py default STARTUPS=kernel-test
  - make -j2
  - make run
