sudo: false
dist: bionic
os:
  - linux
  - osx

language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso

install:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then pyenv global 3.7.1; fi"
  - pip3 install -r tools/requirements.txt
  - cargo install xargo

script:
  - make
