language: c
dist: bionic
sudo: false
os:
  - linux
  - osx

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - llvm
  apt:
    packages:
      - llvm
      - lld
      - clang

install:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then pyenv global 3.7.1; fi"
  - pip3 install -r tools/requirements.txt

script:
  - make defconfig
  - make -j2
