sudo: false
dist: bionic
os:
  - linux
  - osx

language: rust
rust:
  - nightly

cache: cargo

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso
      - python3
      - python3-pip

install:
  - pip3 install -r tools/requirements.txt
  - "cargo install xargo || true"
  - "rustup component add rust-src"

script:
  - make
