language: c
cache:

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic
      env:
        - LLVM_PREFIX=/usr/lib/llvm-9/bin/

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - python
      - qemu
  apt:
    packages:
      - llvm-9
      - lld-9
      - clang-9
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - qemu-system-x86

install:
  - pip3 install --user -r tools/requirements.txt

script:
  - make defconfig
  - sed -ie "s/# CONFIG_TEST_SERVER is not set.*/CONFIG_TEST_SERVER=y/" .config
  - make build -j2
  - make test
