language: c
cache:

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - python
      - mtools
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - mtools

install:
  - "if [[ \"$TRAVIS_OS_NAME\" == osx ]]; then brew link --overwrite python; fi"
  - pip3 install --user -r tools/requirements.txt

script:
  - make defconfig
  - make build -j2
