sudo: false
language: rust
rust:
  - nightly

cache: cargo

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      env: CMD=build
    - os: linux
      dist: bionic
      env: CMD=build LLVM_PREFIX=/usr/bin/ LLVM_SUFFIX=-8
    - os: osx
      osx_image: xcode11.2
      env: CMD=docs
    - os: osx
      osx_image: xcode11.2
      env: CMD=kernel-lint
    - os: osx
      osx_image: xcode11.2
      env: CMD=user-lint
  allow_failures:
    - env: CMD=kernel-lint
    - env: CMD=user-lint

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
      - doxygen
      - graphviz
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

install:
  - pip3 install -r tools/requirements.txt
  - cargo install xargo || true
  - rustup component add rust-src

script:
  - make $CMD

deploy:
  provider: netlify
  edge: true
  dir: build/docs
  on:
    condition: "$CMD = docs"
  site:
    secure: lfgVgOGrxuqs2lpHFcbmTsnY25qFeUe/azGVgP0jF2vr3XO6LuSGxzuHpYKkTNOy/57YGdzlkVqnxznG8WC7o0pT1YdHzTe6xpj2GUU5UZwbCgKtmD2Sk8yInDmdxkpc9qctPumKfz114Pv9/8s4nrwFnedTSr1TpThV8dwTzVr9O58+EhVAV8L8dLxBiz8SKAgF6115HIIlyLyDp/UQ2yvPAINZN39OSJFYyOgxPzp2HkgunxpUq2UivS6ANxAroBb0emKtzik5YgNdlDW7y6fZ0/40R2ZQ7MmBNGjIXE+jQoCEa5XVhQ4TroeoMu3/C+EIt16GMZ5dJ+RdvARC3T/BEUITVeNy2aMfOC6LfiZwfzhZ1KbR1BGeWlT7sq80uM0N8oBYsWZN2am0cLPGmmx4DGHb1jt3f2LGUg7M9f5xaPzyCfGhcTj6MalGprURciAxHj0vTD/LMlD6qYCzFDcP3EgIY5l61SdeT3ZXOk/Pj254JPZdLh2dH4L4JAcdiJIe0WSl3bBDNGhEl/frZmOIf48ijp825+pQyd1nHconrOGU75jZJxADwf0sroRXjyxVPiDQFBVOlkby/bI7mzQyX9LyS9Y/i+6/2Gyt/ENlQMdTURZj64nNPhbTnKzt8TqHSM0KDefntxCZXsTscG8GkMlSuaAIC85p4V6IjX8=
  auth:
    secure: dv25J7BieVo+Zmim6Ynw3L+eM5V1wKQsRGng7FT+mEEL39uJ+6th7d9kjKfL4Hpc0qmZtMVpKEdu+oyzc3irNYnPZe40vk2Coxd5pRAhsK0P+zwGYBL0Z7wtxSA9QLvFBdovGjC+G4ul9pCef0J3uTQ650w+Ix/IL6NnjVKfkP++Gjz/RFnPKWq8Z8ksf6Fyb08EjAcF3TIteASJrKhK0vhH0JE6Pb7m5EWs0Vdk/z2kSY7OPHV7JHKpYSJLjeFJRuEDI8zp+DOKSxf5N8pus6D5sejAg+Tx90vUc923hzh6VoHl41mkTW0pbmRIMGqI56rzrgehrF2r2EaAkCaaAWqLMcnHoNRVNbxQ28yIOmT2RTBwRUB0Z4lQ1V2hoz07BGfX+kQH1ptP6m/U4ITlpwJMNEVmJIzBT8+xO6LNZUOtX1HLVgq7n/AqgT3LB7hSYOnSvM/toWRPrPfOEE2CnXdRwpeVadA2I4cE8BjLRC7l883IRTrFYFZLg88N5vphpCqDTHCNRsI79Rt+k3f87bVuiJP8YZjScqaAL1kQy6pO/n0ZO1uAbxVewwCHSXxYiezLaA+OsGJBurM+lIjn4dv1upVPzLkzAdgGA1HC9pArolESFOz2PKDwPPVLfWDq1volv44oVskW9KGA7h21mVp0ifY8a1wV6iQOcWMr+wQ=
