sudo: false
language: rust
rust:
  - nightly

cache: cargo

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      env: CMD=build
    - os: linux
      dist: bionic
      env: CMD=build LLVM_PREFIX=/usr/bin/ LLVM_SUFFIX=-8
    - os: osx
      osx_image: xcode11.2
      env: CMD=docs
    - os: osx
      osx_image: xcode11.2
      env: CMD=kernel-lint
    - os: osx
      osx_image: xcode11.2
      env: CMD=user-lint
  allow_failures:
    - env: CMD=kernel-lint
    - env: CMD=user-lint

addons:
  homebrew:
    update: true
    packages:
     - llvm
     - qemu
     - xorriso
     - mtools
     - i386-elf-grub
     - doxygen
     - graphviz
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

install:
  - pip3 install -r tools/requirements.txt
  - cargo install xargo || true
  - rustup component add rust-src

script:
  - make $CMD
