language: c
cache: 

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic
      env: LLVM_SUFFIX=-8

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - python
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

install:
  - "if [[ \"$TRAVIS_OS_NAME\" == osx ]]; then brew link --overwrite python; fi"

script:
  - make build
