sudo: false
language: rust
rust:
  - nightly

cache: cargo

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      env: CMD=build
    - os: linux
      dist: bionic
      env: CMD=build LLVM_PREFIX=/usr/bin/ LLVM_SUFFIX=-8

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
      - doxygen
      - graphviz
      - python
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

install:
  - brew link --overwrite python
  - pip3 install -r tools/requirements.txt
  - cargo install xargo || true
  - cargo install mdbook || true
  - rustup component add rust-src

script:
  - make $CMD
