sudo: false
language: rust
rust:
  - nightly

cache: cargo

notifications:
  email: false

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      env: CMD=build
    - os: linux
      dist: bionic
      env: CMD=build LLVM_PREFIX=/usr/bin/ LLVM_SUFFIX=-8
    - os: osx
      osx_image: xcode11.2
      env: CMD=docs
    - os: osx
      osx_image: xcode11.2
      env: CMD=kernel-lint
    - os: osx
      osx_image: xcode11.2
      env: CMD=user-lint
  allow_failures:
    - env: CMD=kernel-lint
    - env: CMD=user-lint

addons:
  homebrew:
    update: true
    packages:
      - llvm
      - qemu
      - xorriso
      - mtools
      - i386-elf-grub
      - doxygen
      - graphviz
  apt:
    packages:
      - llvm-8
      - lld-8
      - clang-8
      - qemu
      - mtools
      - grub2
      - xorriso
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

install:
  - pip3 install -r tools/requirements.txt
  - cargo install xargo || true
  - rustup component add rust-src

script:
  - make $CMD

deploy:
  provider: netlify
  edge: true
  dir: build/docs
  on:
    condition: $CMD = docs
  site:
    secure: lfgVgOGrxuqs2lpHFcbmTsnY25qFeUe/azGVgP0jF2vr3XO6LuSGxzuHpYKkTNOy/57YGdzlkVqnxznG8WC7o0pT1YdHzTe6xpj2GUU5UZwbCgKtmD2Sk8yInDmdxkpc9qctPumKfz114Pv9/8s4nrwFnedTSr1TpThV8dwTzVr9O58+EhVAV8L8dLxBiz8SKAgF6115HIIlyLyDp/UQ2yvPAINZN39OSJFYyOgxPzp2HkgunxpUq2UivS6ANxAroBb0emKtzik5YgNdlDW7y6fZ0/40R2ZQ7MmBNGjIXE+jQoCEa5XVhQ4TroeoMu3/C+EIt16GMZ5dJ+RdvARC3T/BEUITVeNy2aMfOC6LfiZwfzhZ1KbR1BGeWlT7sq80uM0N8oBYsWZN2am0cLPGmmx4DGHb1jt3f2LGUg7M9f5xaPzyCfGhcTj6MalGprURciAxHj0vTD/LMlD6qYCzFDcP3EgIY5l61SdeT3ZXOk/Pj254JPZdLh2dH4L4JAcdiJIe0WSl3bBDNGhEl/frZmOIf48ijp825+pQyd1nHconrOGU75jZJxADwf0sroRXjyxVPiDQFBVOlkby/bI7mzQyX9LyS9Y/i+6/2Gyt/ENlQMdTURZj64nNPhbTnKzt8TqHSM0KDefntxCZXsTscG8GkMlSuaAIC85p4V6IjX8=
  auth:
    secure: dTxk2TMhOtbl8K6rIcLrRi/vpYs1IjlBvU1MCU+DYXrpbkC+LnVdZgvOgLJ3kPP3BuH6O8M6D9MRwKa1OQyUqNUbTc9fPB4F3jnuSfqscKBZ1W9RntVB70qAdwZqs+CReAKwu0YOJWMQKIflLS5dVQoZuDkZrQvEA5ui66NGv7jXBzs/r/sdM9Noo+TxO2CfRAVlqHIZr4+AdH1YqRDqIZN9yx9cAwx2HzA22o7kQcbDDbIFpVgx9xZzBHpxeKsUqi2PDOZw7ESsRVMO2N5akkk/rqFHUI00quRI3n179iS+266L8onJVhHVmADZim49tf5QysinBgiZC+PNDEIo8I3FdcU83NEs0dt5epcavR1dFTA457VgiP9+QubYVYpqhiExnYp1NJO7U+HusON1MvLW9/dzapIWkFc43+/UDFHfMlH+fJxQqLLjF8yB/uvtU+j4qoDI1Nmrfx6sV4kwNwOvc+uNWZhjuIuLy+cwykrDwrlD6afgRrYtBOCbd/fp+955MSt58LX3MXIMF4jgQyOeG+2nBEkdIoZxzTj5iJvoILlgZUFOl6hET5MkuZNosXBcqU4tImKUh54wMei10hAvCTMq0RDTJwhWAppojGLueVPlP9uHqFOK5fHzMJyHDlGyRhKzUuwHHYqeeAr1In33jTCnWqlRDbn802Zmuoc=
