name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            ARCH: x64
          - os: ubuntu-20.04
            ARCH: arm64
          - os: ubuntu-20.04
            ARCH: arm
          - os: ubuntu-20.04
            ARCH: x64_release
          - os: ubuntu-20.04
            ARCH: arm64_release
          - os: ubuntu-20.04
            ARCH: arm_release
          - os: macos-latest
            ARCH: x64
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install apt packages
        if: matrix.os == 'ubuntu-20.04'
        run: >
          sudo apt-get update && sudo apt-get install -y llvm clang lld qemu-system gcc-arm-none-eabi

      - name: Install Homebrew packages
        if: matrix.os == 'macos-latest'
        run: >
          brew install llvm qemu

      - name: Install pip packages
        run: pip3 install --user -r tools/requirements.txt

      - name: Build
        run: |
          cp ci/${{ matrix.ARCH }}.config .config
          make -j2 build

      - name: Test
        run: make -j2 test
