name: Unit Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Rust
        run: |
          rustup override set nightly
          rustup component add rust-src --toolchain nightly

      - name: Install apt packages
        run: >
          sudo apt-get update && sudo apt-get install -y llvm clang lld

      - name: Install pip packages
        run: pip3 install --user -r tools/requirements.txt

      - name: Run all unit tests
        run: |
          make unittest TARGET=libs/unittest
