name: resea.org

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Homebrew packages
        run: brew install mdbook python3

      - name: Install pip packages
        run: pip3 install --user -r tools/requirements.txt

      - name: Build documentation
        run: make website

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod -d build/website
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
