name: resea.org

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install apt packages
        run: >
          sudo apt-get update && sudo apt-get install -y cargo make

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build documentation
        run: make website

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod -d build/website
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
